### ISSUE TITLE
SSL: Certificate verify failed

### ISSUE THREAD

**Issue by NidasioAlberto** [Jacotsu/polibeepsync#50]
I'm on Ubuntu 19, the output on the command line shows this:
``` terminal
Traceback (most recent call last):
  File "/home/nidasioalberto/.local/lib/python3.8/site-packages/polibeepsync/common.py", line 108, in run
    self.user.login()
  File "/home/nidasioalberto/.local/lib/python3.8/site-packages/polibeepsync/common.py", line 698, in login
    first_response = self._login_first_step()
  File "/home/nidasioalberto/.local/lib/python3.8/site-packages/polibeepsync/common.py", line 628, in _login_first_step
    default_lang_page = self.session.get(self.loginurl, timeout=5,
  File "/home/nidasioalberto/.local/lib/python3.8/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/home/nidasioalberto/.local/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/nidasioalberto/.local/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/nidasioalberto/.local/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='beep.metid.polimi.it', port=443): Max retries exceeded with url: /polimi/login (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')))
```

**Comment by Jacotsu** [comment]
Hi, I've already investigated this bug and it seems like a problem generated by a misconfiguration from metid. Basically they didn't include the full chain certificate in the login redirect url.
At the moment i'm waiting a few days to see if metid catches up and fixes it, probably they won't detect it until someone's browser's cache expires.

Anyway, if they don't fix it soon (in a few days) I'm going to try to find a workaround that doesn't disable TLS cert verification

**Comment by NidasioAlberto** [comment]
The app is working again
