### ISSUE TITLE
Timeout when polimi password is about to expire

### ISSUE THREAD

**Issue by malta895** [Jacotsu/polibeepsync#53]
My Polimi password was about to expire, and I couldn't refresh the courses: the software correctly notices me about the password expiring but then it timeouts.
After changing my password everything works, but still I think this is an undesirable behaviour, since Polimi anyways lets the user login until the password is expired.

I use Manjaro Linux (Arch based), polibeepsync is installed from the AUR. 
I'm running Python 3.8.2.

Here is the log, after launching with `polibeepsync --log-level debug` (I removed some personal informations):

```
QVTKWidgetPlugin instantiated

QVTKWidgetPlugin::name

Qt WebEngine seems to be initialized from a plugin. Please set Qt::AA_ShareOpenGLContexts using QCoreApplication::setAttribute before constructing QGuiApplication.
[INFO] polibeepsync.qtgui Data has been loaded successfully.
[INFO] polibeepsync.qtgui User code changed to **********.
[INFO] polibeepsync.common Logging in.
[WARNING] polibeepsync.common Your password is about to expire, change it ASAP
[DEBUG] polibeepsync.common Login url https://beep.metid.polimi.it/user/l**********/home?p_p_id=3&p_p_lifecycle=0&p_p_state=maximized&p_p_mode=view&_3_struts_action=%2Fsearch%2Fsearch&_3_redirect=%2Fuser%2F**************
[ERROR] polibeepsync.common Connection timeout error.
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1322, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/site-packages/urllib3/contrib/pyopenssl.py", line 326, in recv_into
    raise timeout("The read operation timed out")
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.8/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 428, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 335, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='beep.metid.polimi.it', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/polibeepsync/common.py", line 108, in run
    self.user.login()
  File "/usr/lib/python3.8/site-packages/polibeepsync/common.py", line 757, in login
    second_response = self.session.post(url,
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='beep.metid.polimi.it', port=443): Read timed out. (read timeout=10)
```
My password was already stored, and I just clicked on "Refresh list".

Thanks and congratulations for this program, really useful!

**Comment by Jacotsu** [comment]
> exceptions.ReadTimeoutError

This seems to be a problem caused by BeeP's slow response times. Another user had problems with timeouts and I've fixed it by implementing a timeout override flag.
Just start PBS with `polibeepsync --default-timeout 30` to set the timeout time to 30s.

Anyway, I'll try to implement a more graceful timeout handling procedure

**Comment by malta895** [comment]
By now I can't try it anymore because I changed my password, and with the new and not expiring password the issue is completely gone.
