### ISSUE TITLE
Exception when downloading files

### ISSUE THREAD

**Issue by fulcus** [Jacotsu/polibeepsync#68]
While downloading content from beep I often get this traceback
```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/polibeepsync/common.py", line 1058, in download_file
    complete_basename = result.headers['Content-Disposition'] \
  File "/usr/lib/python3/dist-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-disposition'
```

**Comment by Jacotsu** [comment]
Please post the course name and the file name

**Comment by fulcus** [comment]
I can't see the file name, the courses for which this happens right now are: 
[2020-21] - FOUNDATIONS OF OPERATIONS RESEARCH [ FEDERICO MALUCELLI ]
[2020-21] - FORMAL LANGUAGES AND COMPILERS [ LUCA ODDONE BREVEGLIERI ]
[2020-21] - SOFTWARE ENGINEERING 2 [ ELISABETTA DI NITTO, MATTEO ROSSI ]

Another weird thing that I just noticed is that it re downloads (all the "writing into...") files that were already synced.

To have replicable results I deleted and re-synced everything.
I'll copy the full thing so you can see for yourself.

```
Qt WebEngine seems to be initialized from a plugin. Please set Qt::AA_ShareOpenGLContexts using QCoreApplication::setAttribute before constructing QGuiApplication.
[INFO] polibeepsync.qtgui Data has been loaded successfully.
[INFO] polibeepsync.common Logging in.
[INFO] polibeepsync.common Successful login.
[INFO] polibeepsync.common Looking for new courses.
[INFO] polibeepsync.common No new courses found.
[INFO] polibeepsync.common ****DIMENSIONE TOTALE: 68.6MiB
[INFO] polibeepsync.common ****SYNCSIZE: 3.8MiB
[INFO] polibeepsync.common ****ALREADYSYNCED 64.8MiB
[INFO] polibeepsync.common ****DOWNLOADED SIZE setting to 64.8MiB
[INFO] polibeepsync.common writing into /home/fulco/Desktop/poliBeepSync/Data Bases 2 [Piero Fraternali]/1-Lessons/5-JPA/Relevant specifications/JPA 2.0.pdf
[INFO] polibeepsync.common Synced files for [2020-21] - DATA BASES 2 [ PIERO FRATERNALI ]
[INFO] polibeepsync.common ****DIMENSIONE TOTALE: 84.3MiB
[INFO] polibeepsync.common ****SYNCSIZE: 3.8MiB
[INFO] polibeepsync.common ****ALREADYSYNCED 80.5MiB
[INFO] polibeepsync.common ****DOWNLOADED SIZE setting to 80.5MiB
[INFO] polibeepsync.common writing into /home/fulco/Desktop/poliBeepSync/Data Bases 2 [Sara Comai]/1 - Lessons 2020-21/05-JPA/Relevant specifications/JPA 2.0.pdf
[INFO] polibeepsync.common Synced files for [2020-21] - DATA BASES 2 [ SARA COMAI ]
[INFO] polibeepsync.common ****DIMENSIONE TOTALE: 158.6MiB
[INFO] polibeepsync.common File locale non aggiornato: {f} 2020-10-25 12:28:19.940290+01:00 2020-11-18 10:41:00+01:00
[INFO] polibeepsync.common File locale non aggiornato: {f} 2020-11-24 17:13:05.364475+01:00 2020-12-01 12:22:00+01:00
[INFO] polibeepsync.common File locale non aggiornato: {f} 2020-10-05 16:33:27.796129+02:00 2020-11-27 10:46:00+01:00
[INFO] polibeepsync.common ****SYNCSIZE: 283.0KiB
[INFO] polibeepsync.common ****ALREADYSYNCED 158.4MiB
[INFO] polibeepsync.common ****DOWNLOADED SIZE setting to 158.4MiB
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/polibeepsync/common.py", line 1058, in download_file
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/polibeepsync/common.py", line 1058, in download_file
Traceback (most recent call last):
    complete_basename = result.headers['Content-Disposition'] \
  File "/usr/local/lib/python3.8/dist-packages/polibeepsync/common.py", line 1058, in download_file
  File "/usr/lib/python3/dist-packages/requests/structures.py", line 52, in __getitem__
    complete_basename = result.headers['Content-Disposition'] \
  File "/usr/lib/python3/dist-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
    return self._store[key.lower()][1]
KeyError: 'content-disposition'
KeyError: 'content-disposition'
    complete_basename = result.headers['Content-Disposition'] \
  File "/usr/lib/python3/dist-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-disposition'
[INFO] polibeepsync.common writing into /home/fulco/Desktop/poliBeepSync/Foundations Of Operations Research [Federico Malucelli]/material for activities in class/phones.pdf
[INFO] polibeepsync.common Synced files for [2020-21] - FOUNDATIONS OF OPERATIONS RESEARCH [ FEDERICO MALUCELLI ]
[INFO] polibeepsync.common ****DIMENSIONE TOTALE: 35.4MiB
[INFO] polibeepsync.common File locale non aggiornato: {f} 2020-10-07 17:42:26.767479+02:00 2020-10-13 14:31:00+02:00
[INFO] polibeepsync.common File locale non aggiornato: {f} 2020-10-26 13:06:59.370575+01:00 2020-10-29 10:27:00+01:00
[INFO] polibeepsync.common File locale non aggiornato: {f} 2020-09-16 17:22:55.808976+02:00 2020-10-29 10:28:00+01:00
[INFO] polibeepsync.common File locale non aggiornato: {f} 2020-09-16 17:22:55.869899+02:00 2020-10-29 15:17:00+01:00
[INFO] polibeepsync.common ****SYNCSIZE: 322.7KiB
[INFO] polibeepsync.common ****ALREADYSYNCED 35.1MiB
[INFO] polibeepsync.common ****DOWNLOADED SIZE setting to 35.1MiB
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/polibeepsync/common.py", line 1058, in download_file
    complete_basename = result.headers['Content-Disposition'] \
  File "/usr/lib/python3/dist-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-disposition'
[INFO] polibeepsync.common writing into /home/fulco/Desktop/poliBeepSync/Formal Languages And Compilers [Luca Oddone Breveglieri]/Exam texts/Theory/Italiano/LFC - 24 settembre 2008 - ver. 41 -  con soluzioni.pdf
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/polibeepsync/common.py", line 1058, in download_file
    complete_basename = result.headers['Content-Disposition'] \
  File "/usr/lib/python3/dist-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-disposition'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/polibeepsync/common.py", line 1058, in download_file
    complete_basename = result.headers['Content-Disposition'] \
  File "/usr/lib/python3/dist-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-disposition'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/polibeepsync/common.py", line 1058, in download_file
    complete_basename = result.headers['Content-Disposition'] \
  File "/usr/lib/python3/dist-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-disposition'
[INFO] polibeepsync.common Synced files for [2020-21] - FORMAL LANGUAGES AND COMPILERS [ LUCA ODDONE BREVEGLIERI ]
[INFO] polibeepsync.common ****DIMENSIONE TOTALE: 235.3MiB
[INFO] polibeepsync.common ****SYNCSIZE: 132.6MiB
[INFO] polibeepsync.common ****ALREADYSYNCED 102.7MiB
[INFO] polibeepsync.common ****DOWNLOADED SIZE setting to 102.7MiB
[INFO] polibeepsync.common writing into /home/fulco/Desktop/poliBeepSync/Software Engineering 2 [Elisabetta Di Nitto, Matteo Rossi]/Project/R&DD Assignment A.Y. 2020-2021.pdf
[INFO] polibeepsync.common writing into /home/fulco/Desktop/poliBeepSync/Software Engineering 2 [Elisabetta Di Nitto, Matteo Rossi]/Additional material/UTF-8''IEEE Standard for Information Technology—Systems Design—Software Design Descriptions.pdf
[INFO] polibeepsync.common writing into /home/fulco/Desktop/poliBeepSync/Software Engineering 2 [Elisabetta Di Nitto, Matteo Rossi]/Additional material/UTF-8''IEEE Standard for Systems and software engineering — Architecture description.pdf
[INFO] polibeepsync.common writing into /home/fulco/Desktop/poliBeepSync/Software Engineering 2 [Elisabetta Di Nitto, Matteo Rossi]/Exam Preparation/Exams20172018/SE2.EXAM.2018-09-13.WITHSOLUTION.PDF.pdf
[INFO] polibeepsync.common writing into /home/fulco/Desktop/poliBeepSync/Software Engineering 2 [Elisabetta Di Nitto, Matteo Rossi]/Project/RASD to be analysed - A.Y. 2020-2021.pdf
[INFO] polibeepsync.common writing into /home/fulco/Desktop/poliBeepSync/Software Engineering 2 [Elisabetta Di Nitto, Matteo Rossi]/Project/DD to be analysed - A.Y. 2020-2021.pdf
[INFO] polibeepsync.common writing into /home/fulco/Desktop/poliBeepSync/Software Engineering 2 [Elisabetta Di Nitto, Matteo Rossi]/Project/Previous projects/2018-2019/Implementation and Testing Project Assignment - A.Y. 2018-2019.pdf
[INFO] polibeepsync.common writing into /home/fulco/Desktop/poliBeepSync/Software Engineering 2 [Elisabetta Di Nitto, Matteo Rossi]/Project/Previous projects/Example Documents from Past Students/Design Deliverable Sample from A.Y. 2015-2016.pdf
[INFO] polibeepsync.common writing into /home/fulco/Desktop/poliBeepSync/Software Engineering 2 [Elisabetta Di Nitto, Matteo Rossi]/Project/Previous projects/Example Documents from Past Students/RASD Sample from A.Y. 2015-2016.pdf
[INFO] polibeepsync.common writing into /home/fulco/Desktop/poliBeepSync/Software Engineering 2 [Elisabetta Di Nitto, Matteo Rossi]/Project/Previous projects/Example Documents from Past Students/RASD Sample from A.Y. 2016-2017.pdf
[INFO] polibeepsync.common writing into /home/fulco/Desktop/poliBeepSync/Software Engineering 2 [Elisabetta Di Nitto, Matteo Rossi]/Project/Previous projects/2019-2020/RASD to be analysed - A.Y. 2019-2020.pdf
[INFO] polibeepsync.common writing into /home/fulco/Desktop/poliBeepSync/Software Engineering 2 [Elisabetta Di Nitto, Matteo Rossi]/Slides/0. Course Introduction.pdf
[INFO] polibeepsync.common writing into /home/fulco/Desktop/poliBeepSync/Software Engineering 2 [Elisabetta Di Nitto, Matteo Rossi]/Slides/1. Introduction to software engineering.pdf
[INFO] polibeepsync.common writing into /home/fulco/Desktop/poliBeepSync/Software Engineering 2 [Elisabetta Di Nitto, Matteo Rossi]/Slides/2. Alloy.pdf
[INFO] polibeepsync.common writing into /home/fulco/Desktop/poliBeepSync/Software Engineering 2 [Elisabetta Di Nitto, Matteo Rossi]/Slides/2.b Alloy Excercises.pdf
[INFO] polibeepsync.common writing into /home/fulco/Desktop/poliBeepSync/Software Engineering 2 [Elisabetta Di Nitto, Matteo Rossi]/Slides/3.a Requirements engineering Part I.pdf
[INFO] polibeepsync.common writing into /home/fulco/Desktop/poliBeepSync/Software Engineering 2 [Elisabetta Di Nitto, Matteo Rossi]/Slides/3.b Slides from video1 Requirement Engineering Process.pdf
[INFO] polibeepsync.common writing into /home/fulco/Desktop/poliBeepSync/Software Engineering 2 [Elisabetta Di Nitto, Matteo Rossi]/Slides/3.c World and Machine.pdf
[INFO] polibeepsync.common writing into /home/fulco/Desktop/poliBeepSync/Software Engineering 2 [Elisabetta Di Nitto, Matteo Rossi]/Slides/4.a slides from video 2 Elicitation of Requirements.pdf
[INFO] polibeepsync.common writing into /home/fulco/Desktop/poliBeepSync/Software Engineering 2 [Elisabetta Di Nitto, Matteo Rossi]/Slides/4.b slides from video3 Modeling Requirements.pdf
[INFO] polibeepsync.common writing into /home/fulco/Desktop/poliBeepSync/Software Engineering 2 [Elisabetta Di Nitto, Matteo Rossi]/Slides/4.c Scenario and Use Case Example.pdf
[INFO] polibeepsync.common writing into /home/fulco/Desktop/poliBeepSync/Software Engineering 2 [Elisabetta Di Nitto, Matteo Rossi]/Slides/4.d UML for Requirements Engineering.pdf
[INFO] polibeepsync.common writing into /home/fulco/Desktop/poliBeepSync/Software Engineering 2 [Elisabetta Di Nitto, Matteo Rossi]/Slides/4.f Structure of RASD.pdf
[INFO] polibeepsync.common writing into /home/fulco/Desktop/poliBeepSync/Software Engineering 2 [Elisabetta Di Nitto, Matteo Rossi]/Slides/4.e. Examples of RE using Alloy and UML.pdf
[INFO] polibeepsync.common writing into /home/fulco/Desktop/poliBeepSync/Software Engineering 2 [Elisabetta Di Nitto, Matteo Rossi]/Slides/5.a Design Part 1.pdf
[INFO] polibeepsync.common writing into /home/fulco/Desktop/poliBeepSync/Software Engineering 2 [Elisabetta Di Nitto, Matteo Rossi]/Slides/5.b slides from video 4 Design Descriptions and Principles.pdf
[INFO] polibeepsync.common writing into /home/fulco/Desktop/poliBeepSync/Software Engineering 2 [Elisabetta Di Nitto, Matteo Rossi]/Slides/5.c Slides from video 5 Design Process.pdf
[INFO] polibeepsync.common writing into /home/fulco/Desktop/poliBeepSync/Software Engineering 2 [Elisabetta Di Nitto, Matteo Rossi]/Slides/5.e Design case studies.pdf
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/polibeepsync/common.py", line 1058, in download_file
    complete_basename = result.headers['Content-Disposition'] \
  File "/usr/lib/python3/dist-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-disposition'
[INFO] polibeepsync.common writing into /home/fulco/Desktop/poliBeepSync/Software Engineering 2 [Elisabetta Di Nitto, Matteo Rossi]/Slides/5.f. Architecture and Design in Practice.pdf
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/polibeepsync/common.py", line 1058, in download_file
    complete_basename = result.headers['Content-Disposition'] \
  File "/usr/lib/python3/dist-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-disposition'
[INFO] polibeepsync.common Synced files for [2020-21] - SOFTWARE ENGINEERING 2 [ ELISABETTA DI NITTO, MATTEO ROSSI ]
[INFO] polibeepsync.common ****DIMENSIONE TOTALE: 1.6GiB
[INFO] polibeepsync.common ****SYNCSIZE: 1.3MiB
[INFO] polibeepsync.common ****ALREADYSYNCED 1.6GiB
[INFO] polibeepsync.common ****DOWNLOADED SIZE setting to 1.6GiB
[INFO] polibeepsync.common writing into /home/fulco/Desktop/poliBeepSync/Data Mining And Text Mining [Pier Luca Lanzi]/Data/2014/R Scripts/clustering_ex04.R.r
[INFO] polibeepsync.common writing into /home/fulco/Desktop/poliBeepSync/Data Mining And Text Mining [Pier Luca Lanzi]/Data/2014/R Scripts/clustering_ex05.R.r
[INFO] polibeepsync.common writing into /home/fulco/Desktop/poliBeepSync/Data Mining And Text Mining [Pier Luca Lanzi]/Data/2014/R Scripts/clustering_ex01.R.r
[INFO] polibeepsync.common writing into /home/fulco/Desktop/poliBeepSync/Data Mining And Text Mining [Pier Luca Lanzi]/Data/2014/R Scripts/clustering_ex02.R.r
[INFO] polibeepsync.common writing into /home/fulco/Desktop/poliBeepSync/Data Mining And Text Mining [Pier Luca Lanzi]/Data/2014/R Scripts/clustering_ex03.R.r
[INFO] polibeepsync.common writing into /home/fulco/Desktop/poliBeepSync/Data Mining And Text Mining [Pier Luca Lanzi]/Data/2014/R Scripts/clustering_quality.R.r
[INFO] polibeepsync.common writing into /home/fulco/Desktop/poliBeepSync/Data Mining And Text Mining [Pier Luca Lanzi]/Data/2014/R Scripts/maps.R.r
[INFO] polibeepsync.common writing into /home/fulco/Desktop/poliBeepSync/Data Mining And Text Mining [Pier Luca Lanzi]/Notebooks/2017/LogisticRegressionOverfittingExample.ipynb.zip
[INFO] polibeepsync.common writing into /home/fulco/Desktop/poliBeepSync/Data Mining And Text Mining [Pier Luca Lanzi]/Data/2016/Data and description for the course project..zip
[INFO] polibeepsync.common Synced files for [2020-21] - DATA MINING AND TEXT MINING (UIC 583) [ PIER LUCA LANZI ]
[INFO] polibeepsync.common Syncing finished
```

**Comment by Jacotsu** [comment]
The master branch code now downloads those courses without any problems
