### ISSUE TITLE
Course not detected

### ISSUE THREAD

**Issue by fulcus** [Jacotsu/polibeepsync#75]
[Computer security](https://beep.metid.polimi.it/web/3020302) course does not appear at all in the list of courses

**Comment by Jacotsu** [comment]
Get le latest version from git 
click on add course
paste the beep's course link and click ok
sync

**Comment by fulcus** [comment]
I got the latest version following [your instructions](https://github.com/Jacotsu/polibeepsync/issues/72) and now when i run it it gives me this error
```
[INFO] polibeepsync.qtgui New courses will now be automatically synced
No state change slot has been specified <PySide2.QtWidgets.QCheckBox(0x2b48e20, name="addSyncNewCourses") at 0x7f9c32483100>
[INFO] polibeepsync.qtgui All courses will be synced at startup
No state change slot has been specified <PySide2.QtWidgets.QCheckBox(0x2b490d0, name="startupSync") at 0x7f9c32483180>
[INFO] polibeepsync.common Logging in.
[ERROR] polibeepsync.common Login failed.
Traceback (most recent call last):
  File "/home/fulco/projects/external/polibeepsync/polibeepsync/common.py", line 109, in run
    self.user.login()
  File "/home/fulco/projects/external/polibeepsync/polibeepsync/common.py", line 861, in login
    second_response = self.session.post(url,
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 452, in prepare_request
    p.prepare(
  File "/usr/lib/python3/dist-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python3/dist-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/aunicalogin/aunicalogin/controller/IdentificazioneUnica.do?&jaf_currentWFID=main&polij_step=0&__pj0=0&__pj1=5e1c2a853c295679626cdee4c4bcfb63': No schema supplied. Perhaps you meant http:///aunicalogin/aunicalogin/controller/IdentificazioneUnica.do?&jaf_currentWFID=main&polij_step=0&__pj0=0&__pj1=5e1c2a853c295679626cdee4c4bcfb63?
[CRITICAL] polibeepsync.common Something went wront with the login method
Traceback (most recent call last):
  File "/home/fulco/projects/external/polibeepsync/polibeepsync/common.py", line 821, in login
    form = response_tree.xpath('//form')[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fulco/.local/bin/polibeepsync", line 11, in <module>
    load_entry_point('poliBeePsync', 'console_scripts', 'polibeepsync')()
  File "/home/fulco/projects/external/polibeepsync/polibeepsync/qtgui.py", line 596, in main
    frame = MainWindow(args=args)
  File "/home/fulco/projects/external/polibeepsync/polibeepsync/qtgui.py", line 209, in __init__
    self.user.login()
  File "/home/fulco/projects/external/polibeepsync/polibeepsync/common.py", line 825, in login
    if form:
UnboundLocalError: local variable 'form' referenced before assignment
```

**Comment by Jacotsu** [comment]
If you login with the browser do you get a form asking for confirmation?

**Comment by fulcus** [comment]
Not sure what you mean, when I'm not already logged in I log into beep through aunicalogin without further steps.

**Comment by Jacotsu** [comment]
> Not sure what you mean, when I'm not already logged in I log into beep through aunicalogin without further steps.

run the the program as `polibeepsync --log-level debug` and post the resulting log

**Comment by fulcus** [comment]
```
[INFO] polibeepsync.qtgui New courses will now be automatically synced
No state change slot has been specified <PySide2.QtWidgets.QCheckBox(0x2ac29a0, name="addSyncNewCourses") at 0x7fabedf35240>
[INFO] polibeepsync.qtgui All courses will be synced at startup
No state change slot has been specified <PySide2.QtWidgets.QCheckBox(0x2a46cb0, name="startupSync") at 0x7fabedf352c0>
[INFO] polibeepsync.common Logging in.
[DEBUG] polibeepsync.common Login url /aunicalogin/aunicalogin/controller/IdentificazioneUnica.do?&jaf_currentWFID=main&polij_step=0&__pj0=0&__pj1=3a8d560bd8b90fa8c6b01a67f426ea11
[ERROR] polibeepsync.common Login failed.
Traceback (most recent call last):
  File "/home/fulco/projects/external/polibeepsync/polibeepsync/common.py", line 109, in run
    self.user.login()
  File "/home/fulco/projects/external/polibeepsync/polibeepsync/common.py", line 861, in login
    second_response = self.session.post(url,
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 452, in prepare_request
    p.prepare(
  File "/usr/lib/python3/dist-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python3/dist-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/aunicalogin/aunicalogin/controller/IdentificazioneUnica.do?&jaf_currentWFID=main&polij_step=0&__pj0=0&__pj1=3a8d560bd8b90fa8c6b01a67f426ea11': No schema supplied. Perhaps you meant http:///aunicalogin/aunicalogin/controller/IdentificazioneUnica.do?&jaf_currentWFID=main&polij_step=0&__pj0=0&__pj1=3a8d560bd8b90fa8c6b01a67f426ea11?
[DEBUG] polibeepsync.common Login url /aunicalogin/aunicalogin/controller/IdentificazioneUnica.do?&jaf_currentWFID=main&polij_step=0&__pj0=0&__pj1=3a8d560bd8b90fa8c6b01a67f426ea11
Traceback (most recent call last):
  File "/home/fulco/.local/bin/polibeepsync", line 11, in <module>
    load_entry_point('poliBeePsync', 'console_scripts', 'polibeepsync')()
  File "/home/fulco/projects/external/polibeepsync/polibeepsync/qtgui.py", line 596, in main
    frame = MainWindow(args=args)
  File "/home/fulco/projects/external/polibeepsync/polibeepsync/qtgui.py", line 209, in __init__
    self.user.login()
  File "/home/fulco/projects/external/polibeepsync/polibeepsync/common.py", line 861, in login
    second_response = self.session.post(url,
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 452, in prepare_request
    p.prepare(
  File "/usr/lib/python3/dist-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python3/dist-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/aunicalogin/aunicalogin/controller/IdentificazioneUnica.do?&jaf_currentWFID=main&polij_step=0&__pj0=0&__pj1=3a8d560bd8b90fa8c6b01a67f426ea11': No schema supplied. Perhaps you meant http:///aunicalogin/aunicalogin/controller/IdentificazioneUnica.do?&jaf_currentWFID=main&polij_step=0&__pj0=0&__pj1=3a8d560bd8b90fa8c6b01a67f426ea11?
```

**Comment by Jacotsu** [comment]
> [DEBUG] polibeepsync.common Login url /aunicalogin/aunicalogin/controller/IdentificazioneUnica.do?&jaf_currentWFID=ma

ok, working on it

**Comment by alessionossa** [comment]
> > [DEBUG] polibeepsync.common Login url /aunicalogin/aunicalogin/controller/IdentificazioneUnica.do?&jaf_currentWFID=ma
> 
> ok, working on it

Any update on this?

**Comment by Jacotsu** [comment]
Apparently the unicalogin doesn't always return a full url when submitting the form, i've hardcoded the host and i'm testing if it's reliable

**Comment by Jacotsu** [comment]
@alessionossa @fulcus can you try the latest master?

**Comment by fulcus** [comment]
I get this error
```
Traceback (most recent call last):
  File "/home/fulco/.local/bin/polibeepsync", line 11, in <module>
    load_entry_point('poliBeePsync', 'console_scripts', 'polibeepsync')()
  File "/home/fulco/projects/external/polibeepsync/polibeepsync/qtgui.py", line 595, in main
    frame = MainWindow(args=args)
  File "/home/fulco/projects/external/polibeepsync/polibeepsync/qtgui.py", line 151, in __init__
    self.load_data()
  File "/home/fulco/projects/external/polibeepsync/polibeepsync/qtgui.py", line 329, in load_data
    self.db_mgr = DatabaseManager(
  File "/home/fulco/projects/external/polibeepsync/polibeepsync/database_manager.py", line 28, in __init__
    self.__import_serialized_user(pickle.load(f, fix_imports=False))
  File "/home/fulco/projects/external/polibeepsync/polibeepsync/database_manager.py", line 130, in __import_serialized_user
    update_folders_dicts(fold)
  File "/home/fulco/projects/external/polibeepsync/polibeepsync/database_manager.py", line 124, in update_folders_dicts
    update_file_dict(fil, folder)
  File "/home/fulco/projects/external/polibeepsync/polibeepsync/database_manager.py", line 104, in update_file_dict
    fil._file_dict['name'].replace('UTF-8\'\'', '')
KeyError: 'name'
```

**Comment by Jacotsu** [comment]
> I get this error
> 
> ```
> Traceback (most recent call last):
>   File "/home/fulco/.local/bin/polibeepsync", line 11, in <module>
>     load_entry_point('poliBeePsync', 'console_scripts', 'polibeepsync')()
>   File "/home/fulco/projects/external/polibeepsync/polibeepsync/qtgui.py", line 595, in main
>     frame = MainWindow(args=args)
>   File "/home/fulco/projects/external/polibeepsync/polibeepsync/qtgui.py", line 151, in __init__
>     self.load_data()
>   File "/home/fulco/projects/external/polibeepsync/polibeepsync/qtgui.py", line 329, in load_data
>     self.db_mgr = DatabaseManager(
>   File "/home/fulco/projects/external/polibeepsync/polibeepsync/database_manager.py", line 28, in __init__
>     self.__import_serialized_user(pickle.load(f, fix_imports=False))
>   File "/home/fulco/projects/external/polibeepsync/polibeepsync/database_manager.py", line 130, in __import_serialized_user
>     update_folders_dicts(fold)
>   File "/home/fulco/projects/external/polibeepsync/polibeepsync/database_manager.py", line 124, in update_folders_dicts
>     update_file_dict(fil, folder)
>   File "/home/fulco/projects/external/polibeepsync/polibeepsync/database_manager.py", line 104, in update_file_dict
>     fil._file_dict['name'].replace('UTF-8\'\'', '')
> KeyError: 'name'
> ```

Try again with the latest commit

**Comment by alessionossa** [comment]
It works, except for this error when password changes:
```
Traceback (most recent call last):
  File "/products/polibeepsync/polibeepsync/common.py", line 874, in login
    parenttag = login_tree.xpath('table')[3]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/products/polibeepsync/polibeepsync/common.py", line 109, in run
    self.user.login()
  File "/products/polibeepsync/polibeepsync/common.py", line 882, in login
    mainpage = self._do_shibboleth(first_response)
  File "/products/polibeepsync/polibeepsync/common.py", line 775, in _do_shibboleth
    relay_state = hidden_inputs[0]
IndexError: list index out of range
```

**Comment by Jacotsu** [comment]
> It works, except for this error when password changes:
> 
> ```
> Traceback (most recent call last):
>   File "/products/polibeepsync/polibeepsync/common.py", line 874, in login
>     parenttag = login_tree.xpath('table')[3]
> IndexError: list index out of range
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/products/polibeepsync/polibeepsync/common.py", line 109, in run
>     self.user.login()
>   File "/products/polibeepsync/polibeepsync/common.py", line 882, in login
>     mainpage = self._do_shibboleth(first_response)
>   File "/products/polibeepsync/polibeepsync/common.py", line 775, in _do_shibboleth
>     relay_state = hidden_inputs[0]
> IndexError: list index out of range
> ```

You mean when unicalogin asks you to change your password?

**Comment by fulcus** [comment]
It immediately throws an error when I open it
```
[INFO] polibeepsync.qtgui New courses will now be automatically synced
No state change slot has been specified <PySide2.QtWidgets.QCheckBox(0x278cad0, name="addSyncNewCourses") at 0x7f6fb3245440>
[INFO] polibeepsync.qtgui All courses will be synced at startup
No state change slot has been specified <PySide2.QtWidgets.QCheckBox(0x241ce20, name="startupSync") at 0x7f6fb3245500>
[INFO] polibeepsync.common Logging in.
Traceback (most recent call last):
  File "/home/fulco/projects/external/polibeepsync/polibeepsync/common.py", line 874, in login
    parenttag = login_tree.xpath('table')[3]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fulco/projects/external/polibeepsync/polibeepsync/common.py", line 109, in run
    self.user.login()
  File "/home/fulco/projects/external/polibeepsync/polibeepsync/common.py", line 882, in login
    mainpage = self._do_shibboleth(first_response)
  File "/home/fulco/projects/external/polibeepsync/polibeepsync/common.py", line 775, in _do_shibboleth
    relay_state = hidden_inputs[0]
IndexError: list index out of range
Killed
```

**Comment by alessionossa** [comment]
> > It works, except for this error when password changes:
> > ```
> > Traceback (most recent call last):
> >   File "/products/polibeepsync/polibeepsync/common.py", line 874, in login
> >     parenttag = login_tree.xpath('table')[3]
> > IndexError: list index out of range
> > 
> > During handling of the above exception, another exception occurred:
> > 
> > Traceback (most recent call last):
> >   File "/products/polibeepsync/polibeepsync/common.py", line 109, in run
> >     self.user.login()
> >   File "/products/polibeepsync/polibeepsync/common.py", line 882, in login
> >     mainpage = self._do_shibboleth(first_response)
> >   File "/products/polibeepsync/polibeepsync/common.py", line 775, in _do_shibboleth
> >     relay_state = hidden_inputs[0]
> > IndexError: list index out of range
> > ```
> 
> You mean when unicalogin asks you to change your password?

Nope, when I change password in Polibeepsync

**Comment by Jacotsu** [comment]
> It works, except for this error when password changes:
> 
> ```
> Traceback (most recent call last):
>   File "/products/polibeepsync/polibeepsync/common.py", line 874, in login
>     parenttag = login_tree.xpath('table')[3]
> IndexError: list index out of range
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/products/polibeepsync/polibeepsync/common.py", line 109, in run
>     self.user.login()
>   File "/products/polibeepsync/polibeepsync/common.py", line 882, in login
>     mainpage = self._do_shibboleth(first_response)
>   File "/products/polibeepsync/polibeepsync/common.py", line 775, in _do_shibboleth
>     relay_state = hidden_inputs[0]
> IndexError: list index out of range
> ```

Make sure that your password is correct, try the latest commit for convenience since it doesn't crash the thread when a wrong password is inserted



> It immediately throws an error when I open it
> 
> ```
> [INFO] polibeepsync.qtgui New courses will now be automatically synced
> No state change slot has been specified <PySide2.QtWidgets.QCheckBox(0x278cad0, name="addSyncNewCourses") at 0x7f6fb3245440>
> [INFO] polibeepsync.qtgui All courses will be synced at startup
> No state change slot has been specified <PySide2.QtWidgets.QCheckBox(0x241ce20, name="startupSync") at 0x7f6fb3245500>
> [INFO] polibeepsync.common Logging in.
> Traceback (most recent call last):
>   File "/home/fulco/projects/external/polibeepsync/polibeepsync/common.py", line 874, in login
>     parenttag = login_tree.xpath('table')[3]
> IndexError: list index out of range
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/fulco/projects/external/polibeepsync/polibeepsync/common.py", line 109, in run
>     self.user.login()
>   File "/home/fulco/projects/external/polibeepsync/polibeepsync/common.py", line 882, in login
>     mainpage = self._do_shibboleth(first_response)
>   File "/home/fulco/projects/external/polibeepsync/polibeepsync/common.py", line 775, in _do_shibboleth
>     relay_state = hidden_inputs[0]
> IndexError: list index out of range
> Killed
> ```

Are you using the latest commit/zip version?

**Comment by fulcus** [comment]
Now I am and I get basically the same thing
```
[INFO] polibeepsync.qtgui New courses will now be automatically synced
No state change slot has been specified <PySide2.QtWidgets.QCheckBox(0x3aef130, name="addSyncNewCourses") at 0x7fcee7f813c0>
[INFO] polibeepsync.qtgui All courses will be synced at startup
No state change slot has been specified <PySide2.QtWidgets.QCheckBox(0x3aef3a0, name="startupSync") at 0x7fcee7f81480>
[INFO] polibeepsync.common Logging in.
Traceback (most recent call last):
  File "/home/fulco/projects/external/polibeepsync/polibeepsync/common.py", line 880, in login
    parenttag = login_tree.xpath('table')[3]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fulco/projects/external/polibeepsync/polibeepsync/common.py", line 110, in run
    self.user.login()
  File "/home/fulco/projects/external/polibeepsync/polibeepsync/common.py", line 889, in login
    mainpage = self._do_shibboleth(first_response)
  File "/home/fulco/projects/external/polibeepsync/polibeepsync/common.py", line 781, in _do_shibboleth
    relay_state = hidden_inputs[0]
IndexError: list index out of range
Killed
```
Before getting the new version I uninstalled the previous one with `pip3 uninstall polibeepsync`,  so that should work
