### ISSUE TITLE
Linux: Read timed out

### ISSUE THREAD

**Issue by erricodavide** [Jacotsu/polibeepsync#79]
Hi. 

polibeepsync on Windows works flawlessly for me. 

On Linux the situation is different. It sometimes works and sometimes doesn't, but I can't see the reason. 
This is what I get when it doesn't work: 

`2021-03-04  10:30:32	 [INFO] polibeepsync.common Logging in.
2021-03-04  10:30:34	 [INFO] polibeepsync.common Successful login.
2021-03-04  10:30:34	 [INFO] polibeepsync.common Looking for new courses.
2021-03-04  10:30:44	 Traceback (most recent call last):
2021-03-04  10:30:44	 File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 421, in _make_request
2021-03-04  10:30:44	 six.raise_from(e, None)
2021-03-04  10:30:44	 File "<string>", line 3, in raise_from
2021-03-04  10:30:44	 File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 416, in _make_request
2021-03-04  10:30:44	 httplib_response = conn.getresponse()
2021-03-04  10:30:44	 File "/usr/lib/python3.8/http/client.py", line 1347, in getresponse
2021-03-04  10:30:44	 response.begin()
2021-03-04  10:30:44	 File "/usr/lib/python3.8/http/client.py", line 307, in begin
2021-03-04  10:30:44	 version, status, reason = self._read_status()
2021-03-04  10:30:44	 File "/usr/lib/python3.8/http/client.py", line 268, in _read_status
2021-03-04  10:30:44	 line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
2021-03-04  10:30:44	 File "/usr/lib/python3.8/socket.py", line 669, in readinto
2021-03-04  10:30:44	 return self._sock.recv_into(b)
2021-03-04  10:30:44	 File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 326, in recv_into
2021-03-04  10:30:44	 raise timeout("The read operation timed out")
2021-03-04  10:30:44	 socket.timeout: The read operation timed out
2021-03-04  10:30:44	 
2021-03-04  10:30:44	 During handling of the above exception, another exception occurred:
2021-03-04  10:30:44	 
2021-03-04  10:30:44	 Traceback (most recent call last):
2021-03-04  10:30:44	 File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
2021-03-04  10:30:44	 resp = conn.urlopen(
2021-03-04  10:30:44	 File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
2021-03-04  10:30:44	 retries = retries.increment(
2021-03-04  10:30:44	 File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 400, in increment
2021-03-04  10:30:44	 raise six.reraise(type(error), error, _stacktrace)
2021-03-04  10:30:44	 File "/usr/lib/python3/dist-packages/six.py", line 703, in reraise
2021-03-04  10:30:44	 raise value
2021-03-04  10:30:44	 File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
2021-03-04  10:30:44	 httplib_response = self._make_request(
2021-03-04  10:30:44	 File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 423, in _make_request
2021-03-04  10:30:44	 self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
2021-03-04  10:30:44	 File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 330, in _raise_timeout
2021-03-04  10:30:44	 raise ReadTimeoutError(
2021-03-04  10:30:44	 urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='beep.metid.polimi.it', port=443): Read timed out. (read timeout=10)
2021-03-04  10:30:44	 
2021-03-04  10:30:44	 During handling of the above exception, another exception occurred:
2021-03-04  10:30:44	 
2021-03-04  10:30:44	 Traceback (most recent call last):
2021-03-04  10:30:44	 File "/usr/local/lib/python3.8/dist-packages/polibeepsync/common.py", line 73, in run
2021-03-04  10:30:44	 most_recent = self.user.get_online_courses()
2021-03-04  10:30:44	 File "/usr/local/lib/python3.8/dist-packages/polibeepsync/common.py", line 792, in get_online_courses
2021-03-04  10:30:44	 coursespage = self.get_page(self.courses_url)
2021-03-04  10:30:44	 File "/usr/local/lib/python3.8/dist-packages/polibeepsync/common.py", line 607, in get_page
2021-03-04  10:30:44	 response = self.session.get(url, params=params,
2021-03-04  10:30:44	 File "/usr/lib/python3/dist-packages/requests/sessions.py", line 546, in get
2021-03-04  10:30:44	 return self.request('GET', url, **kwargs)
2021-03-04  10:30:44	 File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
2021-03-04  10:30:44	 resp = self.send(prep, **send_kwargs)
2021-03-04  10:30:44	 File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
2021-03-04  10:30:44	 r = adapter.send(request, **kwargs)
2021-03-04  10:30:44	 File "/usr/lib/python3/dist-packages/requests/adapters.py", line 529, in send
2021-03-04  10:30:44	 raise ReadTimeout(e, request=request)
2021-03-04  10:30:44	 requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='beep.metid.polimi.it', port=443): Read timed out. (read timeout=10)
`

**Comment by Jacotsu** [comment]
> Hi.
> 
> polibeepsync on Windows works flawlessly for me.
> 
> On Linux the situation is different. It sometimes works and sometimes doesn't, but I can't see the reason.
> This is what I get when it doesn't work:
> 
> `2021-03-04 10:30:32 [INFO] polibeepsync.common Logging in. 2021-03-04 10:30:34 [INFO] polibeepsync.common Successful login. 2021-03-04 10:30:34 [INFO] polibeepsync.common Looking for new courses. 2021-03-04 10:30:44 Traceback (most recent call last): 2021-03-04 10:30:44 File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 421, in _make_request 2021-03-04 10:30:44 six.raise_from(e, None) 2021-03-04 10:30:44 File "<string>", line 3, in raise_from 2021-03-04 10:30:44 File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 416, in _make_request 2021-03-04 10:30:44 httplib_response = conn.getresponse() 2021-03-04 10:30:44 File "/usr/lib/python3.8/http/client.py", line 1347, in getresponse 2021-03-04 10:30:44 response.begin() 2021-03-04 10:30:44 File "/usr/lib/python3.8/http/client.py", line 307, in begin 2021-03-04 10:30:44 version, status, reason = self._read_status() 2021-03-04 10:30:44 File "/usr/lib/python3.8/http/client.py", line 268, in _read_status 2021-03-04 10:30:44 line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1") 2021-03-04 10:30:44 File "/usr/lib/python3.8/socket.py", line 669, in readinto 2021-03-04 10:30:44 return self._sock.recv_into(b) 2021-03-04 10:30:44 File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 326, in recv_into 2021-03-04 10:30:44 raise timeout("The read operation timed out") 2021-03-04 10:30:44 socket.timeout: The read operation timed out 2021-03-04 10:30:44 2021-03-04 10:30:44 During handling of the above exception, another exception occurred: 2021-03-04 10:30:44 2021-03-04 10:30:44 Traceback (most recent call last): 2021-03-04 10:30:44 File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send 2021-03-04 10:30:44 resp = conn.urlopen( 2021-03-04 10:30:44 File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen 2021-03-04 10:30:44 retries = retries.increment( 2021-03-04 10:30:44 File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 400, in increment 2021-03-04 10:30:44 raise six.reraise(type(error), error, _stacktrace) 2021-03-04 10:30:44 File "/usr/lib/python3/dist-packages/six.py", line 703, in reraise 2021-03-04 10:30:44 raise value 2021-03-04 10:30:44 File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen 2021-03-04 10:30:44 httplib_response = self._make_request( 2021-03-04 10:30:44 File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 423, in _make_request 2021-03-04 10:30:44 self._raise_timeout(err=e, url=url, timeout_value=read_timeout) 2021-03-04 10:30:44 File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 330, in _raise_timeout 2021-03-04 10:30:44 raise ReadTimeoutError( 2021-03-04 10:30:44 urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='beep.metid.polimi.it', port=443): Read timed out. (read timeout=10) 2021-03-04 10:30:44 2021-03-04 10:30:44 During handling of the above exception, another exception occurred: 2021-03-04 10:30:44 2021-03-04 10:30:44 Traceback (most recent call last): 2021-03-04 10:30:44 File "/usr/local/lib/python3.8/dist-packages/polibeepsync/common.py", line 73, in run 2021-03-04 10:30:44 most_recent = self.user.get_online_courses() 2021-03-04 10:30:44 File "/usr/local/lib/python3.8/dist-packages/polibeepsync/common.py", line 792, in get_online_courses 2021-03-04 10:30:44 coursespage = self.get_page(self.courses_url) 2021-03-04 10:30:44 File "/usr/local/lib/python3.8/dist-packages/polibeepsync/common.py", line 607, in get_page 2021-03-04 10:30:44 response = self.session.get(url, params=params, 2021-03-04 10:30:44 File "/usr/lib/python3/dist-packages/requests/sessions.py", line 546, in get 2021-03-04 10:30:44 return self.request('GET', url, **kwargs) 2021-03-04 10:30:44 File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request 2021-03-04 10:30:44 resp = self.send(prep, **send_kwargs) 2021-03-04 10:30:44 File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send 2021-03-04 10:30:44 r = adapter.send(request, **kwargs) 2021-03-04 10:30:44 File "/usr/lib/python3/dist-packages/requests/adapters.py", line 529, in send 2021-03-04 10:30:44 raise ReadTimeout(e, request=request) 2021-03-04 10:30:44 requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='beep.metid.polimi.it', port=443): Read timed out. (read timeout=10) `

For some reason you're getting timed out on linux, try starting polibeepsync with the following command `polibeepsync --default-timeout 60`

**Comment by erricodavide** [comment]
> For some reason you're getting timed out on linux, try starting polibeepsync with the following command `polibeepsync --default-timeout 60`

I've been testing your solution for quite a few days and it's perfectly working now. Thank you!
