### ISSUE TITLE
TypeError: 'str' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by erricodavide** [Jacotsu/polibeepsync#83]
Hi. I'm working on Linux Ubuntu. I've built version 0.80 from source using Makefile, but when I try logging in the program freezes and this is what the log says: 

```
[INFO] polibeepsync.qtgui New courses will now be automatically synced
No state change slot has been specified <PySide2.QtWidgets.QCheckBox(0x2456840, name="addSyncNewCourses") at 0x7fb94ccb5e80>
No state change slot has been specified <PySide2.QtWidgets.QCheckBox(0x1fcb0b0, name="startupSync") at 0x7fb94ccb5f40>
[INFO] polibeepsync.qtgui User code changed to ******** (intentionally hidden).
[INFO] polibeepsync.qtgui Password changed.
[INFO] polibeepsync.common Logging in.
[WARNING] polibeepsync.common Your password is about to expire, change it ASAP
Traceback (most recent call last):
  File "/root/pbs/polibeepsync/common.py", line 110, in run
    self.user.login()
  File "/root/pbs/polibeepsync/common.py", line 845, in login
    url = f'{uri.scheme}://{uri.netloc}{form["action"]}'
  File "src/lxml/etree.pyx", line 1159, in lxml.etree._Element.__getitem__
TypeError: 'str' object cannot be interpreted as an integer
```

Note that I've installed version 0.80 because I had issues with the pre-built version 0.72 that's currently being distributed as the last version (I don't know why, one day the program stopped working and gave me "Login failed error"). This is the log from version 0.72:

```
[INFO] polibeepsync.common Logging in.
[ERROR] polibeepsync.common Login failed.
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/polibeepsync/common.py", line 108, in run
self.user.login()
File "/usr/local/lib/python3.8/dist-packages/polibeepsync/common.py", line 757, in login
second_response = self.session.post(url,
File "/usr/lib/python3/dist-packages/requests/sessions.py", line 581, in post
return self.request('POST', url, data=data, json=json, **kwargs)
File "/usr/lib/python3/dist-packages/requests/sessions.py", line 519, in request
prep = self.prepare_request(req)
File "/usr/lib/python3/dist-packages/requests/sessions.py", line 452, in prepare_request
p.prepare(
File "/usr/lib/python3/dist-packages/requests/models.py", line 313, in prepare
self.prepare_url(url, params)
File "/usr/lib/python3/dist-packages/requests/models.py", line 387, in prepare_url
raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/aunicalogin/aunicalogin/controller/IdentificazioneUnica.do?&jaf_currentWFID=main&polij_step=0&__pj0=0&__pj1=824b9d369d4b8151a52c9e635b4a4d19': No schema supplied. Perhaps you meant http:///aunicalogin/aunicalogin/controller/IdentificazioneUnica.do?&jaf_currentWFID=main&polij_step=0&__pj0=0&__pj1=824b9d369d4b8151a52c9e635b4a4d19?
```

What should I do?

**Comment by Jacotsu** [comment]
Have you tried changing the password?

**Comment by erricodavide** [comment]
> Have you tried changing the password?

It worked. I did not know that the "Password is about to expire" warning could cause this malfunction. 
Problem solved, thank you!
